### ISSUE TITLE
http://localhost:3000/dictionaries.json を開くとエラーが起きる

### ISSUE THREAD

**Issue by ledsun** [pubannotation/pubdictionaries#109]
![image](https://github.com/pubannotation/pubdictionaries/assets/1079508/96c1e5b7-8d2a-4562-8c2d-334e9058cd93)

今回の修正の影響かはわかりません。
そこから確認をお願いします。

**Comment by ChisatoMatoba** [comment]
今回私が編集を始める前のcommitに戻って実行してみても同じエラーで、本番環境でやってみてもエラーになっていました。

URL: https://pubdictionaries.org/dictionaries.json
結果: `{"status":500,"error":"Internal Server Error"}`

<img width="517" alt="image" src="https://github.com/pubannotation/pubdictionaries/assets/149556430/030d0fc8-df73-4835-aef7-9d5acf6b1a20">

どうなるのが正解でしょうか？

**Comment by ledsun** [comment]
調査ありがとうございます。

HTMLでの表示と同様にDictionaryの一覧が表示されて欲しいです。
`dics`の代わりに`Dictionary.all`を渡すだけでいけるかもしれません。
それでダメであればもう少し調査します。
