### ISSUE TITLE
DictionaryにTagを登録できる

### ISSUE THREAD

**Issue by ledsun** [pubannotation/pubdictionaries#54]
## 目的

DictionaryにTagを登録できるようにします。

## 仕様

対象ルート
- /dictionaries/new
- /dictionaries/:id/edit

Tagsテーブルに入力欄を用意してあります。
この入力値を使ってTagモデルを追加・削除してください。
同名のタグが既にある場合は、作り直さずに、元のモデルを残してください。

タグの名前のバリデーションは[Dictionaryと同じ](https://github.com/pubannotation/pubdictionaries/blob/dac8e9d145fc4bc828f1734f91ed3a776a9276f4/app/models/dictionary.rb#L20-L23)にします。

**Comment by ChisatoMatoba** [comment]
@ledsun 
登録したタグは、dictionaryの詳細画面のどこに表示すれば良いでしょうか？もしくは表示不要ですか？
![image](https://github.com/pubannotation/pubdictionaries/assets/149556430/a858af0e-b49e-4594-9676-05a9ffb3a10f)

**Comment by ledsun** [comment]
Active entriesテーブルにカラムを足して、選択できるようにします。
作業は #55 でやってもらう予定です。
