### ISSUE TITLE
Dictionary詳細画面の改修

### ISSUE THREAD

**Issue by ChisatoMatoba** [pubannotation/pubdictionaries#77]
Entryにmode=auto_expandedを追加するにあたり、画面の表示部分を改修する。
改修開始前のスクショと、改修予定の内容を記します。場合によってPRをわけます。

## 

## mode=auto_expanded絞り込み画面
- scoreの降順でソートして表示するようにする
- 一番右の列はチェックボックスとして、その下にゴミ箱マークを設置
- ゴミ箱マークを押下したら、チェックされているentryを削除(blackでもなく、DBから完全削除)、削除前にアラートで確認
![image](https://github.com/pubannotation/pubdictionaries/assets/149556430/bafb9c33-c3a2-47bf-bb9b-5ebe59ea83ed)

**Comment by ChisatoMatoba** [comment]
> mode=auto_expanded絞り込み画面
> 一番右の列はチェックボックスとして、その下にゴミ箱マークを設置
> ゴミ箱マークを押下したら、チェックされているentryを削除(blackでもなく、DBから完全削除)、削除前にアラートで確認

→この仕様で認識合っていますでしょうか？
現状、コードを見る限りでは、一度生成したentryをDBから削除するという操作が見当たらず、destroyというメソッドでもBlackにモード変更するような動作しかしていないです（[entries_controller.rb](https://github.com/pubannotation/pubdictionaries/blob/75550e685c90c1180e17a36ec9bef97218c00a37/app/controllers/entries_controller.rb#L90C6-L90C13)）。
BlackのページからだとGrayにundoするのみです。
auto_expandedの場合は完全に削除、となると、新たにアクションを定義して、DBｋら削除する操作を設定する方針で良いでしょうか？

**Comment by ledsun** [comment]
良いところに気がついてくれました。
削除処理は今回からの追加なので、既存のBlackにモード変更する処理と違っていて大丈夫です。

ただし、削除処理を追加するとなると、destoryメソッドを削除処理にして
Blackモードに変更する処理を、`be_black`などの別の名前にしたいです。
機能追加の前に、メソッド名変更を先にやってください。
